export default data = [
  {
    id: 1,
    vote_average: 1.2,
    path: "https://images.app.goo.gl/QKdHCy3aaqxZCbPM6",
    title: "The queen of the south",
    overview: "a queen who is a drug selle",
    release_date: "2016-12-13",
  },
  {
    id: 2,
    vote_average: 2.2,
    path: "https://images.app.goo.gl/QKdHCy3aaqxZCbPM6",
    title: "Evaluna",
    overview: "a poor girl becomes rich",
    release_date: "2014-05-11",
  },
  {
    id: 3,
    vote_average: 5.2,
    title: "La dona",
    overview: "A rape women who search and kil all her rapper",
    release_date: "2016-08-12",
  },
  {
    id: 4,
    vote_average: 9.2,
    path: "https://images.app.goo.gl/QKdHCy3aaqxZCbPM6",
    title: "Fast and furios 2",
    overview: "car race",
    release_date: "2001-03-05",
  },
  {
    id: 5,
    vote_average: 1.2,
    path: "https://images.app.goo.gl/QKdHCy3aaqxZCbPM6",
    title: "Mme mr",
    overview: "4 couple representing life",
    release_date: " 2021-02-14",
  },
  {
    id: 6,
    vote_average: 6.8,
    path: "https://images.app.goo.gl/QKdHCy3aaqxZCbPM6",
    title: "War room",
    overview: "God is powerful",
    release_date: "2022-3-19",
  },
];